services:
  db:
    image: mysql:8.0.38
    container_name: database-container
    environment:
      MYSQL_ROOT_PASSWORD: masterball
      MYSQL_DATABASE: pokemon
      MYSQL_USER: satoshi
      MYSQL_PASSWORD: pikachu
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database-db/pokemon_data.csv:/docker-entrypoint-initdb.d/pokemon_data.csv
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: ["go", "run", "main.go"]
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:

