services:
  db:
    build: ./database
    container_name: poke_quick_database
    environment:
      MYSQL_DATABASE: poke_quick_db
      MYSQL_USER: satoshi
      MYSQL_PASSWORD: pikachu
      MYSQL_ROOT_PASSWORD: masterball
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/pokemon_data.csv:/docker-entrypoint-initdb.d/pokemon_data.csv
      - ./database/config/my.cnf:/etc/mysql/conf.d/my.cnf
    entrypoint: /bin/bash -c "chmod 644 /etc/mysql/conf.d/my.cnf && chown mysql:mysql /etc/mysql/conf.d/my.cnf && docker-entrypoint.sh mysqld"
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: ["go", "run", "main.go"]
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:

